version: '3.7'

services:
  frea:
    build: .
    restart: always
    ports:
      - "127.0.0.1:8000:3000"
    environment:
      - NEXT_TELEMETRY_DISABLED=1
      - API_URL=https://api.freasearch.org


